org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Djava.io.tmpdir=C:/Users/nsklr/WorkBuddy/2026-08-01-14-49-09/buildtools/tmp
org.gradle.parallel=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
kotlin.daemon.jvmargs=-Djava.io.tmpdir=C:/Users/nsklr/WorkBuddy/2026-08-01-14-49-09/buildtools/tmp
kotlin.incremental=false
# BeeCLD·2v8 令牌已改为用户自行填写（设置页 → BeeCLD令牌），不再打包进APK
