org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Djava.io.tmpdir=C:/Users/nsklr/WorkBuddy/2026-08-01-14-49-09/buildtools/tmp
org.gradle.parallel=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
kotlin.daemon.jvmargs=-Djava.io.tmpdir=C:/Users/nsklr/WorkBuddy/2026-08-01-14-49-09/buildtools/tmp
kotlin.incremental=false
# BeeCLD·2v8 免费令牌：建议在 local.properties 覆盖此值，避免提交到 Git
beecld.token=wat_d89476486ce6673254859b061fc5ae679fab68b2b82259bb
